SELECT CLASS_SESSION.*, COOKING_CLASS.*,
    (SELECT COUNT(*)
        FROM BOOKING
        WHERE BOOKING.CLASS_SESSION_id = CLASS_SESSION.id
        AND BOOKING.status = 'ENROLLED') AS enrolled_count
FROM CLASS_SESSION
JOIN COOKING_CLASS ON CLASS_SESSION.COOKING_CLASS_id = COOKING_CLASS.id