SELECT COUNT(*) AS total_classes
FROM COOKING_CLASS
WHERE USER_email = ?;


SELECT COUNT(*) AS total_sessions
FROM CLASS_SESSION, COOKING_CLASS
WHERE CLASS_SESSION.COOKING_CLASS_id = COOKING_CLASS.id
    AND COOKING_CLASS.USER_email = ?;


SELECT COUNT(*) AS total_enrollments
FROM BOOKING, CLASS_SESSION, COOKING_CLASS
WHERE BOOKING.CLASS_SESSION_id = CLASS_SESSION.id
    AND CLASS_SESSION.COOKING_CLASS_id = COOKING_CLASS.id
    AND COOKING_CLASS.USER_email = ?
    AND BOOKING.status = 'ENROLLED';


SELECT COUNT(DISTINCT BOOKING.user_email) AS total_waiting_students
FROM BOOKING, CLASS_SESSION, COOKING_CLASS
WHERE BOOKING.CLASS_SESSION_id = CLASS_SESSION.id
    AND CLASS_SESSION.COOKING_CLASS_id = COOKING_CLASS.id
    AND COOKING_CLASS.USER_email = ?
    AND BOOKING.status = 'WAITING';


SELECT COOKING_CLASS.cuisine, COUNT(*) AS enrolled_count
FROM BOOKING, CLASS_SESSION, COOKING_CLASS
WHERE BOOKING.CLASS_SESSION_id = CLASS_SESSION.id
    AND CLASS_SESSION.COOKING_CLASS_id = COOKING_CLASS.id
    AND COOKING_CLASS.USER_email = ?
    AND BOOKING.status = 'ENROLLED'
GROUP BY COOKING_CLASS.cuisine
ORDER BY enrolled_count DESC;


SELECT COOKING_CLASS.title, AVG(BOOKING.rating) AS avg_rate
FROM BOOKING, CLASS_SESSION, COOKING_CLASS
WHERE BOOKING.CLASS_SESSION_id = CLASS_SESSION.id
    AND CLASS_SESSION.COOKING_CLASS_id = COOKING_CLASS.id
    AND COOKING_CLASS.USER_email = ?
    AND BOOKING.rating IS NOT NULL
GROUP BY COOKING_CLASS.id
ORDER BY avg_rate DESC;