SELECT CLASS_SESSION.*,
    (SELECT COUNT(*)
        FROM BOOKING
        WHERE BOOKING.CLASS_SESSION_id = CLASS_SESSION.id
        AND BOOKING.status = 'ENROLLED') AS enrolled_count
FROM CLASS_SESSION, COOKING_CLASS
WHERE COOKING_CLASS.id = CLASS_SESSION.COOKING_CLASS_id
    AND COOKING_CLASS.USER_email = ?