SELECT AVG(rating) AS average_rating, COUNT(rating) AS tot_ratings
FROM BOOKING, CLASS_SESSION
WHERE BOOKING.CLASS_SESSION_id = CLASS_SESSION.id
    AND CLASS_SESSION.COOKING_CLASS_id = ?
    AND BOOKING.rating IS NOT NULL