SELECT 
    CLASS_SESSION.id,
    COOKING_CLASS.title,
    COOKING_CLASS.cuisine,
    COOKING_CLASS.chef_name,
    COOKING_CLASS.duration,
    CLASS_SESSION.day_of_week,
    CLASS_SESSION.start_time,
    CLASS_SESSION.kitchen,
    BOOKING.status,
    BOOKING.rating
FROM BOOKING, CLASS_SESSION, COOKING_CLASS
WHERE BOOKING.CLASS_SESSION_id = CLASS_SESSION.id
    AND CLASS_SESSION.COOKING_CLASS_id = COOKING_CLASS.id
    AND BOOKING.USER_email = ?
    AND BOOKING.status IN ('ENROLLED', 'WAITING')